# Taskfile.yml

version: "3"

tasks:
  build-infra:
    desc : build integration test environment
    cmds : 
      - task : db-start
      - task : db-init

  db-start:
    desc: start mssql at local
    cmds:
      - docker-compose -f docker-compose.dev.yml up -d mssql

  db-init :
    desc: create mssql database ,schema and data
    deps: [db-start]
    
  #as required
  db-scripter :
    desc: copy db-schema by mssql-scripter into local
    cmds:
      - mssql-scripter -S 'sd4lab1' -U 'sa' -P 'Ptc12876266' -d 'OPMain' --display-progress -f C:\DataBase\scripter\sd4lab1\OPMain.sql
      - mssql-scripter -S 'sd4lab1' -U 'sa' -P 'Ptc12876266' -d 'OPMain' --display-progress  --include-objects CompareString --data-only -f C:\DataBase\scripter\sd4lab1\CompareString.sql    